### PR TITLE
Add AllStories component test #334

### PR DESCRIPTION
**Pull request by aykutkantas**
For now I could add one test case. In order to manage time effectively, after studying for other pages (ex. Profile page) I will add more test cases.

### CODE REVIEW

**Review by dbaslan — APPROVED** [review]
Looks good, can't wait for the rest! 🥂 Approved

**Review by dbaslan — CHANGES_REQUESTED** [review]
There seems to be an error, can you address it @aykutkantas?

image

**Comment by aykutkantas** [comment]
> There seems to be an error, can you address it @aykutkantas?
> 
> image

this problem has been solved.

**Review by sadikkuzu — APPROVED** [review]

**Review by dbaslan — APPROVED** [review]
Let's go 🚀

**Pull request merged**
