### PR TITLE
Reports->Main Milestone-2

### PR DESCRIPTION
**Pull request by sadikkuzu**
This PR covers all documentation implementations including mainly Milestone-2 report.

Initially, it is a draft pull-request at the moment.

Later on, it will be converted to actual pr.

Due Date: 06 December 2023

Presentation Date: 04 December 2023

Software Release Date: 03 December 2023

[GitHub G1-milestone2 details](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/milestone/3) [GitHub G1-mobile-milestone2 details](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/milestone/2)

### CODE REVIEW

**Comment by sadikkuzu** [comment]
@dbaslan hi,
since there are [some line fixings](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/190/commits/f1d8b467115236c0cf9031e668f947d65a9f4a08),
could you please pull the latest version into HackMD file?
thanks in advance.

**Comment by sadikkuzu** [comment]
pre-commit.ci autofix

**Review by dbaslan — APPROVED** [review]
LGTM! 🥂

**Review by ckertam — APPROVED** [review]
Well done by all the team! 🥂

**Pull request merged**
