### PR TITLE
Fix remaining wrong fonts #282

### PR DESCRIPTION
**Pull request by dbaslan**
This fixes the font for following user memories in the homepage.

### CODE REVIEW

**Comment by sadikkuzu** [comment]
@dbaslan hi,
Update branch, please.

update-branch

**Comment by dbaslan** [comment]
Branch updated

**Comment by sadikkuzu** [comment]
@dbaslan hi,
Could you replace other "Inter" fonts to "Josefine" in your branch?

**Comment by sadikkuzu** [comment]
I mean, our focus should be font-fix, not "following user memories" page etc.
Thanks in advance 🙏🏼

**Comment by dbaslan** [comment]
@sadikkuzu Oğuz and I changed every instance of Inter to Josefine and merged the branch twice with dev. This is one final pull request for branch 240 to fix the last instance of Inter we missed 👍

**Comment by sadikkuzu** [comment]
Ok, then, in our one final pull request for branch 240, let's change these remaining ones:
Inter-milan

**Comment by dbaslan** [comment]
@sadikkuzu Thank you! 🙏 You saved us another pull request 😄 Fixed remaining fonts

**Review by sadikkuzu — APPROVED** [review]
LGTM 🥂

**Pull request merged**
