### PR TITLE
Add Register Unit Test #332

### PR DESCRIPTION
**Pull request by aykutkantas**
Unit test for register page has been added, executed and passed.

### CODE REVIEW

**Review by sadikkuzu — CHANGES_REQUESTED** [review]
@aykutkantas hi,
There are some warnings in Frontend CI Test pipeline.
Could you please fix them?

register-test

**Comment by aykutkantas** [comment]
> @aykutkantas hi, There are some warnings in Frontend CI Test pipeline. Could you please fix them?
> 
> register-test

This is about some unsupported styles such as not flex-direction, yes flexDirection. Register.js has been improved. There are same warnings in login.js also. I will improve them also. Thanks for your attention. :)

**Comment by dbaslan** [comment]
I will take care of the warnings for the remaining pages 👍

**Comment by aykutkantas** [comment]
> > @aykutkantas hi, There are some warnings in Frontend CI Test pipeline. Could you please fix them?
> > register-test
> 
> This is about some unsupported styles such as not flex-direction, yes flexDirection. Register.js has been improved. There are same warnings in login.js also. I will improve them also. Thanks for your attention. :)

By the way, in order to improve this, when I changed register.js register page is broken. Because it is designing type of register page. I think we shouldn't improve it at this moment, all of our tests have been passed. At the end we can check code improvements. What do you think? @sadikkuzu 
 
Screenshot 2023-12-24 at 00 16 41

Screenshot 2023-12-24 at 00 12 26

**Review by dbaslan — APPROVED** [review]
@aykutkantas @sadikkuzu If that's alright with you, let me handle the warnings concerning camelCase. I'll approve this PR and I'll get it done on a different branch

**Comment by sadikkuzu** [comment]
> @aykutkantas @sadikkuzu If that's alright with you, let me handle the warnings concerning camelCase. I'll approve this PR and I'll get it done on a different branch

@dbaslan Sure 👍🏼 
I'll approve this PR too

Thanks @aykutkantas 🎉

**Comment by aykutkantas** [comment]
> @aykutkantas @sadikkuzu If that's alright with you, let me handle the warnings concerning camelCase. I'll approve this PR and I'll get it done on a different branch

sure for me too, thanks in advance. 👍

**Review by sadikkuzu — APPROVED** [review]
LGTM 🥂

**Pull request merged**
