### PR TITLE
Feature/75 frontend refinements

### LINKED ISSUE #75: Frontend Refinements
* Fix non-unique ids
* Remove unnecessary console logs

### PR DESCRIPTION
**Pull request by aykutkantas**
Resolves #75

### CODE REVIEW

**Review by ckertam — CHANGES_REQUESTED** [review]
If we make those changes can we also remove the comment outed lines in those Component files 🥂

**Comment by aykutkantas** [comment]
Comment outed lines removed

**Review by ckertam — APPROVED** [review]
LGTM !

**Review by sadikkuzu — APPROVED** [review]
LGTM 🚀

**Pull request merged**
