### PR TITLE
Feature/81 follow user button counter issue

### LINKED ISSUE #81: Follow user button & counter issue
When I follow a user the counter does not change. 

Also, if I am following a user the "Follow" button should change to "Unfollow"

image

### PR DESCRIPTION
**Pull request by aykutkantas**
Resolves #81

### CODE REVIEW

**Review by sadikkuzu — APPROVED** [review]
LGTM 👍🏼

**Review by sadikkuzu — CHANGES_REQUESTED** [review]
This branch is out-of-date with the base branch
Merge the latest changes from `dev` into this branch.

image

**Comment by sadikkuzu** [comment]
I'm "sadik1" user in my local containerized web app. And I follow "sadik2" user.


(1)
When I go to "sadik2" profile page,
I see follower count:1 which is ok.
But I see "Follow" button there, which is not ok.
image

(2)
When I click Follow button, 
followers count becomes zero, which is ok
image

(3)
When I click Follow button again,
followers count becomes 1 again, which is ok
and button label becomes Unfollow, which is perfectly ok
image

The only case that must be focused on here is the first case (1).

@aykutkantas Could you handle that bug in this PR as well?

**Comment by ckertam** [comment]
There were also another issue that has to be resolved. That is mentioned in #81  #107 

Also the issue @sadikkuzu mentioned is resolved too.

**Review by oguzsenna — APPROVED** [review]
More passion, more energy

**Comment by sadikkuzu** [comment]
> There were also another issue that has to be resolved. That is mentioned in #81 #107
> 
> Also the issue @sadikkuzu mentioned is resolved too.
> 
> Can you please check again?

Thank you so much.
I'll check asap.

**Review by sadikkuzu — APPROVED** [review]
Cool, it's ok now 😎 👍🏼 

(1)
image

(2)
image

(3)
image

**Pull request merged**
